module.exports = {
  'uswds': {
    owner: '18f',
    repo: 'federalist-uswds-template',
    branch: 'master',
    example: 'https://federalist-proxy.app.cloud.gov/site/18f/federalist-uswds-template/',
    title: 'U.S. Web Design Standards',
    description: 'A flexible Jekyll implementation of the U.S. Web Design Standards',
  },
  'team': {
    owner: '18f',
    repo: 'federalist-modern-team-template',
    branch: 'master',
    example: 'https://pages.18f.gov/federalist-modern-team-template/',
    title: 'Multi-page Template',
    description: 'Simple Jekyll site to showcase the work of an organization',
  },
  'landing': {
    owner: '18f',
    repo: 'federalist-landing-page-template',
    branch: 'master',
    example: 'http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/18F/federalist-landing-page-template/',
    title: 'Single-page template',
    description: 'Single page to host information about a specific topic or report',
  },
  'developer': {
    owner: 'USG-Website-Templates',
    repo: 'developer-hub',
    branch: 'gh-pages',
    example: 'http://usg-website-templates.github.io/developer-hub/',
    title: 'A developer hub for API documentation',
    description: 'A template for developer hubs and API docs',
  },
  'microsite': {
    owner: 'USG-Website-Templates',
    repo: 'microsite-template',
    branch: 'gh-pages',
    example: 'https://usg-website-templates.github.io/microsite-template/',
    title: 'Basic microsite',
    description: 'A site template for a small site',
  },
};
