swagger: '2.0'
info:
  title: Federalist API
  description: API for interacting with Federalist
  version: "0.0.0"
host: federalist-staging.fr.cloud.gov
schemes:
  - https
basePath: /v0
produces:
  - application/json
paths:
  /build:
    get:
      summary: Fetch all of the user's builds
      responses:
        200:
          description: An array of builds
          schema:
            type: array
            items:
              $ref: "Build.json"
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
  /build/{id}:
    parameters:
    - name: id
      in: path
      description: The id of the build
      type: integer
      required: true
    get:
      summary: Fetch a build by its ID
      responses:
        200:
          description: The build object specified by the ID
          schema:
            $ref: "Build.json"
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
        404:
          description: Not found
          schema:
            $ref: "Error.json"
  /build/{id}/status/{token}:
    parameters:
    - name: id
      in: path
      description: The id of the build
      type: integer
      required: true
    - name: token
      in: path
      description: Federalist's secret build token.
      type: string
      required: true
    post:
      summary: |
        Update a build's status. This endpoint is designed to be used by the
        build container to update the build's status when the build is done with
        its work.
      parameters:
      - name: status
        in: body
        description: The build container's status
        required: true
        schema:
          type: object
          properties:
            status:
              description: The build container's exit code
              type: string
            message:
              description: The error message associated with the build. Empty if status is "0"
              type: string
      responses:
        200:
          description: Acknowledgement that the build has been updated
        400:
          description: Bad request
          schema:
            $ref: "Error.json"
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
        404:
          description: Not found
          schema:
            $ref: "Error.json"
  /build/{id}/restart:
    parameters:
      - name: id
        in: path
        description: The id of the build
        type: integer
        required: true
    post:
      summary: Create a new build mirrored after the given build.
      responses:
        200:
          description: Acknowledgement that the build has been restarted
          schema:
            $ref: "Build.json"
        400:
          description: Bad request
          schema:
            $ref: "Error.json"
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
        404:
          description: Not found
          schema:
            $ref: "Error.json"
  /build/{build_id}/log/{token}:
    parameters:
    - name: build_id
      in: path
      description: The id of the build
      type: integer
      required: true
    - name: token
      in: path
      description: Federalist's secret build token.
      type: string
      required: true
    post:
      summary: Add build container output to a build by creating a build log record
      responses:
        200:
          description: Acknowledgement that the build log was created
          schema:
            $ref: "BuildLog.json"
        400:
          description: Bad request
          schema:
            $ref: "Error.json"
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
        404:
          description: Not found
          schema:
            $ref: "Error.json"
  /build/{build_id}/log:
    parameters:
    - name: build_id
      in: path
      description: The id of the build
      type: integer
      required: true
    get:
      summary: Fetch all build logs associated with a build
      responses:
        200:
          description: An array of the build logs associated with the build
          schema:
            type: array
            items:
              $ref: "BuildLog.json"
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
        404:
          description: Not found
          schema:
            $ref: "Error.json"
  /site:
    get:
      summary: Fetch all of the current user's sites
      responses:
        200:
          description: An array of all sites associated with the current user
          schema:
            type: array
            items:
              $ref: "Site.json"
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
    post:
      summary: Create a site
      parameters:
        - name: site
          in: body
          schema:
            type: object
            properties:
              config:
                type: string
                description: Jekyll configs for the site.
              defaultBranch:
                type: string
                description: The default branch for the site.
              engine:
                type: string
                description: The build engine to use when building the new site
              owner:
                type: string
                description: The owner of the GitHub repo for the site
              publicPreview:
                type: string
                description: Whether public previews are enabled for the site
              repository:
                type: string
                description: The name of the GitHub repository for the site
              template:
                type: string
                description: |
                  The name of a Federalist site template. If provided, the a new
                  repo will be created from the repo for the given template. If
                  a template is not provided, Federalist will not create a new
                  repo and will instead expect to build a site from an existing
                  repo.
      responses:
        200:
          description: The newly created site
          schema:
            $ref: "Site.json"
        400:
          description: Bad request
          schema:
            $ref: "Error.json"
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
  /site/{id}:
    parameters:
    - name: id
      in: path
      description: The id of the site
      type: integer
      required: true
    get:
      summary: Fetch the data for a Federalist site
      responses:
        200:
          description: The site object for the given ID
          schema:
            $ref: "Site.json"
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
        404:
          description: Not found
          schema:
            $ref: "Error.json"
    put:
      summary: Update the data for a Federalist site. This action will trigger a rebuild of the site.
      parameters:
        - name: site
          in: body
          schema:
            type: object
            properties:
              config:
                type: string
                description: Jekyll configs for the site.
              defaultBranch:
                type: string
                description: The default branch for the site.
              engine:
                type: string
                description: The build engine to use when building the new site
              owner:
                type: string
                description: The owner of the GitHub repo for the site
              publicPreview:
                type: string
                description: Whether public previews are enabled for the site
              repository:
                type: string
                description: The name of the GitHub repository for the site
      responses:
        200:
          description: The updated site object
          schema:
            $ref: "Site.json"
        400:
          description: Bad request
          schema:
            $ref: "Error.json"
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
        404:
          description: Not found
          schema:
            $ref: "Error.json"
    delete:
      summary: Delete a site from Federalist
      responses:
        200:
          description: Acknowledgement that the site was deleted
          schema:
            $ref: "Site.json"
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
        404:
          description: Not found
          schema:
            $ref: "Error.json"
  /me:
    get:
      summary: Fetch data for the current user
      responses:
        200:
          description: A user object representing the current Federalist user
          schema:
            $ref: "CurrentUser.json"
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
  /user/{id}:
    parameters:
    - name: id
      in: path
      description: The id of the site
      type: integer
      required: true
    get:
      summary: Fetch data for a Federalist user
      responses:
        200:
          description: A user object for the given ID
          schema:
            $ref: "User.json"
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
        404:
          description: Not found
          schema:
            $ref: "Error.json"
  /user/usernames:
    get:
      summary: Fetch the usernames for every user in federalist
      responses:
        200:
          description: An array of usernames with an element for each Federalist user
          schema:
            type: array
            items:
              type: string
        403:
          description: Not authorized
          schema:
            $ref: "Error.json"
