FROM node:12.17

RUN apt-get update && apt-get install -y git

RUN mkdir -p /app

WORKDIR /app
COPY . /app

RUN rm -rf admin-client \
  yarn config set cache-folder /app/.yarn-cache

EXPOSE 1337 8888 8080
