name: federalistapp
memory: 512MB
instances: 2
env: production
env_postfix: ''
log_level: info
feature_auth_github: 'true'
feature_auth_uaa: 'false'
feature_proxy_edge_links: 'false'
feature_proxy_edge_dynamo: 'false'
feature_bull_site_build_queue: 'false'
uaa_host: https://uaa.fr.cloud.gov
new_relic_app_name: web
smtp_cert: NA
smtp_from: NA
smtp_host: NA
smtp_password: NA
smtp_port: NA
smtp_user: NA