product: federalist
name: federalistapp-staging
domain: federalistapp-staging.18f.gov
app_subdomain: ''
memory: 256MB
instances: 2
env: staging
env_postfix: -staging
log_level: verbose
feature_auth_github: 'true'
feature_auth_uaa: 'false'
feature_proxy_edge_links: 'false'
feature_proxy_edge_dynamo: 'false'
feature_bull_site_build_queue: 'true'
uaa_host: https://uaa.fr-stage.cloud.gov
new_relic_app_name: web-staging
smtp_cert: ((smtp_cert))
smtp_from: ((smtp_from))
smtp_host: ((smtp_host))
smtp_password: ((smtp_password))
smtp_port: ((smtp_port))
smtp_user: ((smtp_user))