module.exports = {
  adminHostname: process.env.ADMIN_HOSTNAME || 'http://localhost:3000',
  hostname: process.env.APP_HOSTNAME || 'http://localhost:1337',
  app_env: process.env.APP_ENV || 'development',
  homepageUrl: process.env.HOMEPAGE_URL || 'http://localhost:4000',
  s3ServicePlanId: process.env.S3_SERVICE_PLAN_ID || 'myFederalistS3BrokerGuid',
  proxySiteTable: process.env.PROXY_SITE_TABLE || 'federalist-proxy-dev',
  proxyPreviewHost: process.env.FEDERALIST_PREVIEW_HOSTNAME || 'http://*.sites-local.localhost:1337',
  sandboxDays: Number(process.env.SANDBOX_DAYS || 90),
  sandboxNotices: Number(process.env.SANDBOX_NOTICES || 2),
  sandboxNoticeDaysInterval: Number(process.env.SANDBOX_NOTICE_DAYS_INTERVAL || 7),
  domain: process.env.DOMAIN || 'localhost:1337',
  proxyDomain: process.env.PROXY_DOMAIN || 'localhost:1337',
  product: process.env.PRODUCT || 'pages',
};
