module.exports = {
  report: {
    owner: '18f',
    repo: 'federalist-report-template',
    branch: 'master',
    example: 'https://federalist-report-template.18f.gov',
    title: 'Basic Report Template',
    description: 'A basic template to host a set of pages about a recent report or order',
    thumb: '/images/report.thumb.png',
  },
  team: {
    owner: '18f',
    repo: 'federalist-modern-team-template',
    branch: 'master',
    example: 'https://federalist-modern-team-template.18f.gov',
    title: 'Modern Team Template',
    description: 'Simple Jekyll site to showcase the work of an organization',
    thumb: '/images/team.thumb.png',
  },
  landing: {
    owner: '18f',
    repo: 'federalist-landing-page-template',
    branch: 'master',
    example: 'https://federalist-landing-template.18f.gov',
    title: 'Landing Page Template',
    description: 'Single page to host information about a specific topic or report',
    thumb: '/images/landing.thumb.png',
  },
  uswds: {
    owner: '18f',
    repo: 'federalist-uswds-template',
    branch: 'master',
    example: 'https://federalist-uswds-template.18f.gov',
    title: 'U.S. Web Design Standards Template',
    description: 'A flexible Jekyll implementation of the U.S. Web Design Standards',
    thumb: '/images/uswds.thumb.png',
  },
};
