module.exports = {
  report: {
    owner: '18f',
    repo: 'federalist-report-template',
    branch: 'master',
    example: 'https://federalist-report-template.18f.gov',
    title: 'Basic report template',
    description: 'A basic template to host a set of pages about a recent report or order.',
    thumb: '/images/federalist-report-template.jpg',
  },
  team: {
    owner: '18f',
    repo: 'federalist-modern-team-template',
    branch: 'master',
    example: 'https://federalist-modern-team-template.18f.gov',
    title: 'Modern team template',
    description: 'A simple template to showcase the work of an organization.',
    thumb: '/images/federalist-modern-team-template.jpg',
  },
  landing: {
    owner: '18f',
    repo: 'federalist-landing-page-template',
    branch: 'master',
    example: 'https://federalist-landing-template.18f.gov',
    title: 'Landing page template',
    description: 'A one page template to show information about a specific topic or report.',
    thumb: '/images/federalist-landing-template.jpg',
  },
  uswds: {
    owner: '18f',
    repo: 'federalist-uswds-template',
    branch: 'master',
    example: 'https://federalist-uswds-template.18f.gov',
    title: 'USWDS template',
    description: 'A flexible template using the U.S. Web Design Standards.',
    thumb: '/images/federalist-uswds-template.jpg',
  },
  redirect: {
    owner: '18f',
    repo: 'federalist-uswds-template',
    branch: 'redirect-config',
    example: 'https://federalist-proxy.app.cloud.gov/preview/18f/federalist-uswds-template/redirect-config/',
    title: 'Redirect template',
    description: 'A simple redirect template.',
    thumb: '/images/federalist-redirect-template.jpg',
  },
};
