// from https://www.zaproxy.org/docs/alerts/
// names deduped with
// BUILD_SCAN_RULES.forEach(rule => {
//   const nameMatch = BUILD_SCAN_RULES
//     .filter(r => r.id !== rule.id).find(r => r.name === rule.name)
//   if (nameMatch && rule.id.includes('-')) {
//     rule.name = `${rule.name} - ${rule.id.slice(-1)}`
//   }
// })
// and axe-core
// (cat lib/rules/*.json | jq --slurp 'map({id, name: .metadata.help, type: "a11y" })')
const BUILD_SCAN_RULES = [
  {
    id: '0',
    name: 'Directory Browsing',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/0/',
  },
  {
    id: '2',
    name: 'Private IP Disclosure',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/2/',
  },
  {
    id: '3',
    name: 'Session ID in URL Rewrite',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/3/',
  },
  {
    id: '3-1',
    name: 'Session ID in URL Rewrite - 1',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/3-1/',
  },
  {
    id: '3-2',
    name: 'Session ID in URL Rewrite - 2',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/3-2/',
  },
  {
    id: '3-3',
    name: 'Referer Exposes Session ID',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/3-3/',
  },
  {
    id: '6',
    name: 'Path Traversal',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/6/',
  },
  {
    id: '6-1',
    name: 'Path Traversal - 1',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/6-1/',
  },
  {
    id: '6-2',
    name: 'Path Traversal - 2',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/6-2/',
  },
  {
    id: '6-3',
    name: 'Path Traversal - 3',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/6-3/',
  },
  {
    id: '6-4',
    name: 'Path Traversal - 4',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/6-4/',
  },
  {
    id: '6-5',
    name: 'Path Traversal - 5',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/6-5/',
  },
  {
    id: '7',
    name: 'Remote File Inclusion',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/7/',
  },
  {
    id: '41',
    name: 'Source Code Disclosure - Git ',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/41/',
  },
  {
    id: '42',
    name: 'Source Code Disclosure - SVN',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/42/',
  },
  {
    id: '43',
    name: 'Source Code Disclosure - File Inclusion',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/43/',
  },
  {
    id: '10003',
    name: 'Vulnerable JS Library',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10003/',
  },
  {
    id: '10009',
    name: 'In Page Banner Information Leak',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10009/',
  },
  {
    id: '10010',
    name: 'Cookie No HttpOnly Flag',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10010/',
  },
  {
    id: '10011',
    name: 'Cookie Without Secure Flag',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10011/',
  },
  {
    id: '10015',
    name: 'Re-examine Cache-control Directives',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10015/',
  },
  {
    id: '10016',
    name: 'Web Browser XSS Protection Not Enabled',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10016/',
  },
  {
    id: '10017',
    name: 'Cross-Domain JavaScript Source File Inclusion',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10017/',
  },
  {
    id: '10019',
    name: 'Content-Type Header Missing',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10019/',
  },
  {
    id: '10019-1',
    name: 'Content-Type Header Missing - 1',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10019-1/',
  },
  {
    id: '10019-2',
    name: 'Content-Type Header Empty',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10019-2/',
  },
  {
    id: '10020',
    name: 'Anti-clickjacking Header',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10020/',
  },
  {
    id: '10020-1',
    name: 'Missing Anti-clickjacking Header',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10020-1/',
  },
  {
    id: '10020-2',
    name: 'Multiple X-Frame-Options Header Entries',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10020-2/',
  },
  {
    id: '10020-3',
    name: 'X-Frame-Options Defined via META (Non-compliant with Spec)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10020-3/',
  },
  {
    id: '10020-4',
    name: 'X-Frame-Options Setting Malformed',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10020-4/',
  },
  {
    id: '10021',
    name: 'X-Content-Type-Options Header Missing',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10021/',
  },
  {
    id: '10023',
    name: 'Information Disclosure - Debug Error Messages',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10023/',
  },
  {
    id: '10024',
    name: 'Information Disclosure - Sensitive Information in URL',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10024/',
  },
  {
    id: '10025',
    name: 'Information Disclosure - Sensitive Information in HTTP Referrer Header',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10025/',
  },
  {
    id: '10026',
    name: 'HTTP Parameter Override',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10026/',
  },
  {
    id: '10027',
    name: 'Information Disclosure - Suspicious Comments',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10027/',
  },
  {
    id: '10028',
    name: 'Open Redirect',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10028/',
  },
  {
    id: '10029',
    name: 'Cookie Poisoning',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10029/',
  },
  {
    id: '10030',
    name: 'User Controllable Charset',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10030/',
  },
  {
    id: '10031',
    name: 'User Controllable HTML Element Attribute (Potential XSS)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10031/',
  },
  {
    id: '10032',
    name: 'Viewstate',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10032/',
  },
  {
    id: '10032-1',
    name: 'Potential IP Addresses Found in the Viewstate',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10032-1/',
  },
  {
    id: '10032-2',
    name: 'Emails Found in the Viewstate',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10032-2/',
  },
  {
    id: '10032-3',
    name: 'Old Asp.Net Version in Use',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10032-3/',
  },
  {
    id: '10032-4',
    name: 'Viewstate without MAC Signature (Unsure)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10032-4/',
  },
  {
    id: '10032-5',
    name: 'Viewstate without MAC Signature (Sure)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10032-5/',
  },
  {
    id: '10032-6',
    name: 'Split Viewstate in Use',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10032-6/',
  },
  {
    id: '10033',
    name: 'Directory Browsing',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10033/',
  },
  {
    id: '10034',
    name: 'Heartbleed OpenSSL Vulnerability (Indicative)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10034/',
  },
  {
    id: '10035',
    name: 'Strict-Transport-Security Header',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10035/',
  },
  {
    id: '10035-1',
    name: 'Strict-Transport-Security Header Not Set',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10035-1/',
  },
  {
    id: '10035-2',
    name: 'Strict-Transport-Security Disabled',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10035-2/',
  },
  {
    id: '10035-3',
    name: 'Strict-Transport-Security Multiple Header Entries (Non-compliant with Spec)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10035-3/',
  },
  {
    id: '10035-4',
    name: 'Strict-Transport-Security Header on Plain HTTP Response',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10035-4/',
  },
  {
    id: '10035-5',
    name: 'Strict-Transport-Security Missing Max-Age (Non-compliant with Spec)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10035-5/',
  },
  {
    id: '10035-6',
    name: 'Strict-Transport-Security Defined via META (Non-compliant with Spec)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10035-6/',
  },
  {
    id: '10035-7',
    name: 'Strict-Transport-Security Max-Age Malformed (Non-compliant with Spec)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10035-7/',
  },
  {
    id: '10035-8',
    name: 'Strict-Transport-Security Malformed Content (Non-compliant with Spec)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10035-8/',
  },
  {
    id: '10036',
    name: 'HTTP Server Response Header',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10036/',
  },
  {
    id: '10036-1',
    name: 'Server Leaks its Webserver Application via "Server" HTTP Response Header Field',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10036-1/',
  },
  {
    id: '10036-2',
    name: 'Server Leaks Version Information via "Server" HTTP Response Header Field',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10036-2/',
  },
  {
    id: '10037',
    name: 'Server Leaks Information via "X-Powered-By" HTTP Response Header Field(s)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10037/',
  },
  {
    id: '10038',
    name: 'Content Security Policy (CSP) Header Not Set',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10038/',
  },
  {
    id: '10038-1',
    name: 'Content Security Policy (CSP) Header Not Set - 1',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10038-1/',
  },
  {
    id: '10038-2',
    name: 'Obsolete Content Security Policy (CSP) Header Found',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10038-2/',
  },
  {
    id: '10038-3',
    name: 'Content Security Policy (CSP) Report-Only Header Found',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10038-3/',
  },
  {
    id: '10039',
    name: 'X-Backend-Server Header Information Leak',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10039/',
  },
  {
    id: '10040',
    name: 'Secure Pages Include Mixed Content',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10040/',
  },
  {
    id: '10041',
    name: 'HTTP to HTTPS Insecure Transition in Form Post',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10041/',
  },
  {
    id: '10042',
    name: 'HTTPS to HTTP Insecure Transition in Form Post',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10042/',
  },
  {
    id: '10043',
    name: 'User Controllable JavaScript Event (XSS)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10043/',
  },
  {
    id: '10044',
    name: 'Big Redirect Detected (Potential Sensitive Information Leak)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10044/',
  },
  {
    id: '10044-1',
    name: 'Big Redirect Detected (Potential Sensitive Information Leak) - 1',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10044-1/',
  },
  {
    id: '10044-2',
    name: 'Multiple HREFs Redirect Detected (Potential Sensitive Information Leak)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10044-2/',
  },
  {
    id: '10045',
    name: 'Source Code Disclosure - /WEB-INF Folder',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10045/',
  },
  {
    id: '10045-1',
    name: 'Source Code Disclosure - /WEB-INF Folder - 1',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10045-1/',
  },
  {
    id: '10045-2',
    name: 'Properties File Disclosure - /WEB-INF folder',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10045-2/',
  },
  {
    id: '10046',
    name: 'Insecure Component',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10046/',
  },
  {
    id: '10047',
    name: 'HTTPS Content Available via HTTP',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10047/',
  },
  {
    id: '10048',
    name: 'Remote Code Execution - Shell Shock',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10048/',
  },
  {
    id: '10048-1',
    name: 'Remote Code Execution - Shell Shock - 1',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10048-1/',
  },
  {
    id: '10048-2',
    name: 'Remote Code Execution - Shell Shock - 2',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10048-2/',
  },
  {
    id: '10049',
    name: 'Content Cacheability',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10049/',
  },
  {
    id: '10049-1',
    name: 'Non-Storable Content',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10049-1/',
  },
  {
    id: '10049-2',
    name: 'Storable but Non-Cacheable Content',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10049-2/',
  },
  {
    id: '10049-3',
    name: 'Storable and Cacheable Content',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10049-3/',
  },
  {
    id: '10050',
    name: 'Retrieved from Cache',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10050/',
  },
  {
    id: '10050-1',
    name: 'Retrieved from Cache - 1',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10050-1/',
  },
  {
    id: '10050-2',
    name: 'Retrieved from Cache - 2',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10050-2/',
  },
  {
    id: '10051',
    name: 'Relative Path Confusion',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10051/',
  },
  {
    id: '10052',
    name: 'X-ChromeLogger-Data (XCOLD) Header Information Leak',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10052/',
  },
  {
    id: '10053',
    name: 'Apache Range Header DoS (CVE-2011-3192)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10053/',
  },
  {
    id: '10054',
    name: 'Cookie without SameSite Attribute',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10054/',
  },
  {
    id: '10054-1',
    name: 'Cookie without SameSite Attribute - 1',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10054-1/',
  },
  {
    id: '10054-2',
    name: 'Cookie with SameSite Attribute None',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10054-2/',
  },
  {
    id: '10054-3',
    name: 'Cookie with Invalid SameSite Attribute',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10054-3/',
  },
  {
    id: '10055',
    name: 'CSP',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10055/',
  },
  {
    id: '10055-1',
    name: 'CSP: X-Content-Security-Policy',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10055-1/',
  },
  {
    id: '10055-2',
    name: 'CSP: X-WebKit-CSP',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10055-2/',
  },
  {
    id: '10055-3',
    name: 'CSP: Notices',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10055-3/',
  },
  {
    id: '10055-4',
    name: 'CSP: Wildcard Directive',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10055-4/',
  },
  {
    id: '10055-5',
    name: 'CSP: script-src unsafe-inline',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10055-5/',
  },
  {
    id: '10055-6',
    name: 'CSP: style-src unsafe-inline',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10055-6/',
  },
  {
    id: '10055-7',
    name: 'CSP: script-src unsafe-hashes',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10055-7/',
  },
  {
    id: '10055-8',
    name: 'CSP: style-src unsafe-hashes',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10055-8/',
  },
  {
    id: '10055-9',
    name: 'CSP: Malformed Policy (Non-ASCII)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10055-9/',
  },
  {
    id: '10055-10',
    name: 'CSP: script-src unsafe-eval',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10055-10/',
  },
  {
    id: '10055-11',
    name: 'CSP: Meta Policy Invalid Directive',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10055-11/',
  },
  {
    id: '10055-12',
    name: 'CSP: Header &amp; Meta',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10055-12/',
  },
  {
    id: '10056',
    name: 'X-Debug-Token Information Leak',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10056/',
  },
  {
    id: '10057',
    name: 'Username Hash Found',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10057/',
  },
  {
    id: '10058',
    name: 'GET for POST',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10058/',
  },
  {
    id: '10061',
    name: 'X-AspNet-Version Response Header',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10061/',
  },
  {
    id: '10062',
    name: 'PII Disclosure',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10062/',
  },
  {
    id: '10063',
    name: 'Permissions Policy Header Not Set',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10063/',
  },
  {
    id: '10063-1',
    name: 'Permissions Policy Header Not Set - 1',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10063-1/',
  },
  {
    id: '10063-2',
    name: 'Deprecated Feature Policy Header Set',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10063-2/',
  },
  {
    id: '10070',
    name: 'Use of SAML',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10070/',
  },
  {
    id: '10094',
    name: 'Base64 Disclosure',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10094/',
  },
  {
    id: '10094-1',
    name: 'ASP.NET ViewState Disclosure',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10094-1/',
  },
  {
    id: '10094-2',
    name: 'ASP.NET ViewState Integrity',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10094-2/',
  },
  {
    id: '10094-3',
    name: 'Base64 Disclosure - 3',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10094-3/',
  },
  {
    id: '10095',
    name: 'Backup File Disclosure',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10095/',
  },
  {
    id: '10096',
    name: 'Timestamp Disclosure - Unix',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10096/',
  },
  {
    id: '10097',
    name: 'Hash Disclosure - MD4 / MD5',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10097/',
  },
  {
    id: '10098',
    name: 'Cross-Domain Misconfiguration',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10098/',
  },
  {
    id: '10099',
    name: 'Source Code Disclosure - PHP',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10099/',
  },
  {
    id: '10101',
    name: 'Access Control Issue - Improper Authentication',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10101/',
  },
  {
    id: '10102',
    name: 'Access Control Issue - Improper Authorization',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10102/',
  },
  {
    id: '10103',
    name: 'Image Exposes Location or Privacy Data',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10103/',
  },
  {
    id: '10104',
    name: 'User Agent Fuzzer',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10104/',
  },
  {
    id: '10105',
    name: 'Weak Authentication Method',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10105/',
  },
  {
    id: '10105-1',
    name: 'Authentication Credentials Captured',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10105-1/',
  },
  {
    id: '10105-2',
    name: 'Weak Authentication Method - 2',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10105-2/',
  },
  {
    id: '10106',
    name: 'HTTP Only Site',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10106/',
  },
  {
    id: '10107',
    name: 'Httpoxy - Proxy Header Misuse',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10107/',
  },
  {
    id: '10108',
    name: 'Reverse Tabnabbing',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10108/',
  },
  {
    id: '10109',
    name: 'Modern Web Application',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10109/',
  },
  {
    id: '10110',
    name: 'Dangerous JS Functions',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10110/',
  },
  {
    id: '10111',
    name: 'Authentication Request Identified',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10111/',
  },
  {
    id: '10112',
    name: 'Session Management Response Identified',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10112/',
  },
  {
    id: '10113',
    name: 'Verification Request Identified',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10113/',
  },
  {
    id: '10202',
    name: 'Absence of Anti-CSRF Tokens',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/10202/',
  },
  {
    id: '20012',
    name: 'Anti-CSRF Tokens Check',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20012/',
  },
  {
    id: '20014',
    name: 'HTTP Parameter Pollution',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20014/',
  },
  {
    id: '20015',
    name: 'Heartbleed OpenSSL Vulnerability',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20015/',
  },
  {
    id: '20016',
    name: 'Cross-Domain Misconfiguration',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20016/',
  },
  {
    id: '20016-1',
    name: 'Cross-Domain Misconfiguration - Adobe - Read',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20016-1/',
  },
  {
    id: '20016-2',
    name: 'Cross-Domain Misconfiguration - Adobe - Send',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20016-2/',
  },
  {
    id: '20016-3',
    name: 'Cross-Domain Misconfiguration - Silverlight',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20016-3/',
  },
  {
    id: '20017',
    name: 'Source Code Disclosure - CVE-2012-1823',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20017/',
  },
  {
    id: '20018',
    name: 'Remote Code Execution - CVE-2012-1823',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20018/',
  },
  {
    id: '20019',
    name: 'External Redirect',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20019/',
  },
  {
    id: '20019-1',
    name: 'External Redirect - 1',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20019-1/',
  },
  {
    id: '20019-2',
    name: 'External Redirect - 2',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20019-2/',
  },
  {
    id: '20019-3',
    name: 'External Redirect - 3',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20019-3/',
  },
  {
    id: '20019-4',
    name: 'External Redirect - 4',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/20019-4/',
  },
  {
    id: '30001',
    name: 'Buffer Overflow',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/30001/',
  },
  {
    id: '30002',
    name: 'Format String Error',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/30002/',
  },
  {
    id: '30003',
    name: 'Integer Overflow Error',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/30003/',
  },
  {
    id: '40003',
    name: 'CRLF Injection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40003/',
  },
  {
    id: '40008',
    name: 'Parameter Tampering',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40008/',
  },
  {
    id: '40009',
    name: 'Server Side Include',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40009/',
  },
  {
    id: '40012',
    name: 'Cross Site Scripting (Reflected)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40012/',
  },
  {
    id: '40013',
    name: 'Session Fixation',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40013/',
  },
  {
    id: '40014',
    name: 'Cross Site Scripting (Persistent)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40014/',
  },
  {
    id: '40015',
    name: 'LDAP Injection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40015/',
  },
  {
    id: '40016',
    name: 'Cross Site Scripting (Persistent) - Prime',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40016/',
  },
  {
    id: '40017',
    name: 'Cross Site Scripting (Persistent) - Spider',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40017/',
  },
  {
    id: '40018',
    name: 'SQL Injection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40018/',
  },
  {
    id: '40019',
    name: 'SQL Injection - MySQL',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40019/',
  },
  {
    id: '40020',
    name: 'SQL Injection - Hypersonic SQL',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40020/',
  },
  {
    id: '40021',
    name: 'SQL Injection - Oracle',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40021/',
  },
  {
    id: '40022',
    name: 'SQL Injection - PostgreSQL',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40022/',
  },
  {
    id: '40023',
    name: 'Possible Username Enumeration',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40023/',
  },
  {
    id: '40024',
    name: 'SQL Injection - SQLite',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40024/',
  },
  {
    id: '40025',
    name: 'Proxy Disclosure',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40025/',
  },
  {
    id: '40026',
    name: 'Cross Site Scripting (DOM Based)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40026/',
  },
  {
    id: '40027',
    name: 'SQL Injection - MsSQL',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40027/',
  },
  {
    id: '40028',
    name: 'ELMAH Information Leak',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40028/',
  },
  {
    id: '40029',
    name: 'Trace.axd Information Leak',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40029/',
  },
  {
    id: '40031',
    name: 'Out of Band XSS',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40031/',
  },
  {
    id: '40032',
    name: '.htaccess Information Leak',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40032/',
  },
  {
    id: '40033',
    name: 'NoSQL Injection - MongoDB',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40033/',
  },
  {
    id: '40034',
    name: '.env Information Leak',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40034/',
  },
  {
    id: '40035',
    name: 'Hidden File Found',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40035/',
  },
  {
    id: '40036',
    name: 'JWT Scan Rule',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40036/',
  },
  {
    id: '40038',
    name: 'Bypassing 403',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40038/',
  },
  {
    id: '40039',
    name: 'Web Cache Deception',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40039/',
  },
  {
    id: '40040',
    name: 'CORS Header',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40040/',
  },
  {
    id: '40040-1',
    name: 'CORS Header - 1',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40040-1/',
  },
  {
    id: '40040-2',
    name: 'CORS Misconfiguration - 2',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40040-2/',
  },
  {
    id: '40040-3',
    name: 'CORS Misconfiguration',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40040-3/',
  },
  {
    id: '40041',
    name: 'File Upload',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40041/',
  },
  {
    id: '40042',
    name: 'Spring Actuator Information Leak',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40042/',
  },
  {
    id: '40043',
    name: 'Log4Shell',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40043/',
  },
  {
    id: '40043-1',
    name: 'Log4Shell (CVE-2021-44228)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40043-1/',
  },
  {
    id: '40043-2',
    name: 'Log4Shell (CVE-2021-45046)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40043-2/',
  },
  {
    id: '40044',
    name: 'Exponential Entity Expansion (Billion Laughs Attack)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40044/',
  },
  {
    id: '40045',
    name: 'Spring4Shell',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40045/',
  },
  {
    id: '40046',
    name: 'Server Side Request Forgery',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40046/',
  },
  {
    id: '40047',
    name: 'Text4shell (CVE-2022-42889)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/40047/',
  },
  {
    id: '50007',
    name: 'ExtensionGraphQl',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/50007/',
  },
  {
    id: '50007-1',
    name: 'GraphQL Endpoint Supports Introspection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/50007-1/',
  },
  {
    id: '50007-2',
    name: 'GraphQL Server Implementation Identified',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/50007-2/',
  },
  {
    id: '90001',
    name: 'Insecure JSF ViewState',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90001/',
  },
  {
    id: '90002',
    name: 'Java Serialization Object',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90002/',
  },
  {
    id: '90003',
    name: 'Sub Resource Integrity Attribute Missing',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90003/',
  },
  {
    id: '90004',
    name: 'Insufficient Site Isolation Against Spectre Vulnerability',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90004/',
  },
  {
    id: '90004-1',
    name: 'Insufficient Site Isolation Against Spectre Vulnerability - 1',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90004-1/',
  },
  {
    id: '90004-2',
    name: 'Insufficient Site Isolation Against Spectre Vulnerability - 2',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90004-2/',
  },
  {
    id: '90004-3',
    name: 'Insufficient Site Isolation Against Spectre Vulnerability - 3',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90004-3/',
  },
  {
    id: '90005',
    name: 'Fetch Metadata Request Headers',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90005/',
  },
  {
    id: '90005-1',
    name: 'Sec-Fetch-Site Header is Missing',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90005-1/',
  },
  {
    id: '90005-2',
    name: 'Sec-Fetch-Mode Header is Missing',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90005-2/',
  },
  {
    id: '90005-3',
    name: 'Sec-Fetch-Dest Header is Missing',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90005-3/',
  },
  {
    id: '90005-4',
    name: 'Sec-Fetch-User Header is Missing',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90005-4/',
  },
  {
    id: '90005-5',
    name: 'Sec-Fetch-Site Header Has an Invalid Value',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90005-5/',
  },
  {
    id: '90005-6',
    name: 'Sec-Fetch-Mode Header Has an Invalid Value',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90005-6/',
  },
  {
    id: '90005-7',
    name: 'Sec-Fetch-Dest Header Has an Invalid Value',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90005-7/',
  },
  {
    id: '90005-8',
    name: 'Sec-Fetch-User Header Has an Invalid Value',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90005-8/',
  },
  {
    id: '90011',
    name: 'Charset Mismatch',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90011/',
  },
  {
    id: '90017',
    name: 'XSLT Injection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90017/',
  },
  {
    id: '90018',
    name: 'Advanced SQL Injection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90018/',
  },
  {
    id: '90019',
    name: 'Server Side Code Injection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90019/',
  },
  {
    id: '90019-1',
    name: 'Server Side Code Injection - PHP Code Injection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90019-1/',
  },
  {
    id: '90019-2',
    name: 'Server Side Code Injection - ASP Code Injection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90019-2/',
  },
  {
    id: '90020',
    name: 'Remote OS Command Injection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90020/',
  },
  {
    id: '90021',
    name: 'XPath Injection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90021/',
  },
  {
    id: '90022',
    name: 'Application Error Disclosure',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90022/',
  },
  {
    id: '90023',
    name: 'XML External Entity Attack',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90023/',
  },
  {
    id: '90024',
    name: 'Generic Padding Oracle',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90024/',
  },
  {
    id: '90025',
    name: 'Expression Language Injection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90025/',
  },
  {
    id: '90026',
    name: 'SOAP Action Spoofing',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90026/',
  },
  {
    id: '90027',
    name: 'Cookie Slack Detector',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90027/',
  },
  {
    id: '90028',
    name: 'Insecure HTTP Method',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90028/',
  },
  {
    id: '90029',
    name: 'SOAP XML Injection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90029/',
  },
  {
    id: '90030',
    name: 'WSDL File Detection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90030/',
  },
  {
    id: '90033',
    name: 'Loosely Scoped Cookie',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90033/',
  },
  {
    id: '90034',
    name: 'Cloud Metadata Potentially Exposed',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90034/',
  },
  {
    id: '90035',
    name: 'Server Side Template Injection',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90035/',
  },
  {
    id: '90036',
    name: 'Server Side Template Injection (Blind)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90036/',
  },
  {
    id: '90039',
    name: 'NoSQL Injection - MongoDB (Time Based)',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/90039/',
  },
  {
    id: '110001',
    name: 'Application Error Disclosure via WebSockets',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/110001/',
  },
  {
    id: '110002',
    name: 'Base64 Disclosure in WebSocket message',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/110002/',
  },
  {
    id: '110003',
    name: 'Information Disclosure - Debug Error Messages via WebSocket',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/110003/',
  },
  {
    id: '110004',
    name: 'Email address found in WebSocket message',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/110004/',
  },
  {
    id: '110005',
    name: 'Personally Identifiable Information via WebSocket',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/110005/',
  },
  {
    id: '110006',
    name: 'Private IP Disclosure via WebSocket',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/110006/',
  },
  {
    id: '110007',
    name: 'Username Hash Found in WebSocket message',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/110007/',
  },
  {
    id: '110008',
    name: 'Information Disclosure - Suspicious Comments in XML via WebSocket',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/110008/',
  },
  {
    id: '110009',
    name: 'Full Path Disclosure',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/110009/',
  },
  {
    id: '120000',
    name: 'Information Disclosure - Information in Browser Storage',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/120000/',
  },
  {
    id: '120000-1',
    name: 'Information Disclosure - Information in Browser localStorage',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/120000-1/',
  },
  {
    id: '120000-2',
    name: 'Information Disclosure - Information in Browser sessionStorage',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/120000-2/',
  },
  {
    id: '120001',
    name: 'Information Disclosure - Sensitive Information in Browser Storage',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/120001/',
  },
  {
    id: '120001-1',
    name: 'Information Disclosure - Sensitive Information in Browser localStorage',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/120001-1/',
  },
  {
    id: '120001-2',
    name: 'Information Disclosure - Sensitive Information in Browser sessionStorage',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/120001-2/',
  },
  {
    id: '120002',
    name: 'Information Disclosure - JWT in Browser Storage',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/120002/',
  },
  {
    id: '120002-1',
    name: 'Information Disclosure - JWT in Browser localStorage',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/120002-1/',
  },
  {
    id: '120002-2',
    name: 'Information Disclosure - JWT in Browser sessionStorage',
    type: 'owasp-zap',
    url: 'https://www.zaproxy.org/docs/alerts/120002-2/',
  },
  {
    id: 'accesskeys',
    name: 'accesskey attribute value should be unique',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/accesskeys',
  },
  {
    id: 'area-alt',
    name: 'Active <area> elements must have alternate text',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/area-alt',
  },
  {
    id: 'aria-allowed-attr',
    name: 'Elements must only use supported ARIA attributes',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-allowed-attr',
  },
  {
    id: 'aria-allowed-role',
    name: 'ARIA role should be appropriate for the element',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-allowed-role',
  },
  {
    id: 'aria-braille-equivalent',
    name: 'aria-braille attributes must have a non-braille equivalent',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-braille-equivalent',
  },
  {
    id: 'aria-command-name',
    name: 'ARIA commands must have an accessible name',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-command-name',
  },
  {
    id: 'aria-conditional-attr',
    name: "ARIA attributes must be used as specified for the element's role",
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-conditional-attr',
  },
  {
    id: 'aria-deprecated-role',
    name: 'Deprecated ARIA roles must not be used',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-deprecated-role',
  },
  {
    id: 'aria-dialog-name',
    name: 'ARIA dialog and alertdialog nodes should have an accessible name',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-dialog-name',
  },
  {
    id: 'aria-hidden-body',
    name: 'aria-hidden="true" must not be present on the document body',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-hidden-body',
  },
  {
    id: 'aria-hidden-focus',
    name: 'ARIA hidden element must not be focusable or contain focusable elements',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-hidden-focus',
  },
  {
    id: 'aria-input-field-name',
    name: 'ARIA input fields must have an accessible name',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-input-field-name',
  },
  {
    id: 'aria-meter-name',
    name: 'ARIA meter nodes must have an accessible name',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-meter-name',
  },
  {
    id: 'aria-progressbar-name',
    name: 'ARIA progressbar nodes must have an accessible name',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-progressbar-name',
  },
  {
    id: 'aria-prohibited-attr',
    name: 'Elements must only use permitted ARIA attributes',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-prohibited-attr',
  },
  {
    id: 'aria-required-attr',
    name: 'Required ARIA attributes must be provided',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-required-attr',
  },
  {
    id: 'aria-required-children',
    name: 'Certain ARIA roles must contain particular children',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-required-children',
  },
  {
    id: 'aria-required-parent',
    name: 'Certain ARIA roles must be contained by particular parents',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-required-parent',
  },
  {
    id: 'aria-roledescription',
    name: 'aria-roledescription must be on elements with a semantic role',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-roledescription',
  },
  {
    id: 'aria-roles',
    name: 'ARIA roles used must conform to valid values',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-roles',
  },
  {
    id: 'aria-text',
    name: '"role=text" should have no focusable descendants',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-text',
  },
  {
    id: 'aria-toggle-field-name',
    name: 'ARIA toggle fields must have an accessible name',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-toggle-field-name',
  },
  {
    id: 'aria-tooltip-name',
    name: 'ARIA tooltip nodes must have an accessible name',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-tooltip-name',
  },
  {
    id: 'aria-treeitem-name',
    name: 'ARIA treeitem nodes should have an accessible name',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-treeitem-name',
  },
  {
    id: 'aria-valid-attr-value',
    name: 'ARIA attributes must conform to valid values',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-valid-attr-value',
  },
  {
    id: 'aria-valid-attr',
    name: 'ARIA attributes must conform to valid names',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/aria-valid-attr',
  },
  {
    id: 'audio-caption',
    name: '<audio> elements must have a captions track',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/audio-caption',
  },
  {
    id: 'autocomplete-valid',
    name: 'autocomplete attribute must be used correctly',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/autocomplete-valid',
  },
  {
    id: 'avoid-inline-spacing',
    name: 'Inline text spacing must be adjustable with custom stylesheets',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/avoid-inline-spacing',
  },
  {
    id: 'blink',
    name: '<blink> elements are deprecated and must not be used',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/blink',
  },
  {
    id: 'button-name',
    name: 'Buttons must have discernible text',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/button-name',
  },
  {
    id: 'bypass',
    name: 'Page must have means to bypass repeated blocks',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/bypass',
  },
  {
    id: 'color-contrast-enhanced',
    name: 'Elements must meet enhanced color contrast ratio thresholds',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/color-contrast-enhanced',
  },
  {
    id: 'color-contrast',
    name: 'Elements must meet minimum color contrast ratio thresholds',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/color-contrast',
  },
  {
    id: 'css-orientation-lock',
    name: 'CSS Media queries must not lock display orientation',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/css-orientation-lock',
  },
  {
    id: 'definition-list',
    name: '<dl> elements must only directly contain properly-ordered <dt> and <dd> groups, <script>, <template> or <div> elements',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/definition-list',
  },
  {
    id: 'dlitem',
    name: '<dt> and <dd> elements must be contained by a <dl>',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/dlitem',
  },
  {
    id: 'document-title',
    name: 'Documents must have <title> element to aid in navigation',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/document-title',
  },
  {
    id: 'duplicate-id-active',
    name: 'IDs of active elements must be unique',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/duplicate-id-active',
  },
  {
    id: 'duplicate-id-aria',
    name: 'IDs used in ARIA and labels must be unique',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/duplicate-id-aria',
  },
  {
    id: 'duplicate-id',
    name: 'id attribute value must be unique',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/duplicate-id',
  },
  {
    id: 'empty-heading',
    name: 'Headings should not be empty',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/empty-heading',
  },
  {
    id: 'empty-table-header',
    name: 'Table header text should not be empty',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/empty-table-header',
  },
  {
    id: 'focus-order-semantics',
    name: 'Elements in the focus order should have an appropriate role',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/focus-order-semantics',
  },
  {
    id: 'form-field-multiple-labels',
    name: 'Form field must not have multiple label elements',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/form-field-multiple-labels',
  },
  {
    id: 'frame-focusable-content',
    name: 'Frames with focusable content must not have tabindex=-1',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/frame-focusable-content',
  },
  {
    id: 'frame-tested',
    name: 'Frames should be tested with axe-core',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/frame-tested',
  },
  {
    id: 'frame-title-unique',
    name: 'Frames must have a unique title attribute',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/frame-title-unique',
  },
  {
    id: 'frame-title',
    name: 'Frames must have an accessible name',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/frame-title',
  },
  {
    id: 'heading-order',
    name: 'Heading levels should only increase by one',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/heading-order',
  },
  {
    id: 'hidden-content',
    name: 'Hidden content on the page should be analyzed',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/hidden-content',
  },
  {
    id: 'html-has-lang',
    name: '<html> element must have a lang attribute',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/html-has-lang',
  },
  {
    id: 'html-lang-valid',
    name: '<html> element must have a valid value for the lang attribute',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/html-lang-valid',
  },
  {
    id: 'html-xml-lang-mismatch',
    name: 'HTML elements with lang and xml:lang must have the same base language',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/html-xml-lang-mismatch',
  },
  {
    id: 'identical-links-same-purpose',
    name: 'Links with the same name must have a similar purpose',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/identical-links-same-purpose',
  },
  {
    id: 'image-alt',
    name: 'Images must have alternate text',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/image-alt',
  },
  {
    id: 'image-redundant-alt',
    name: 'Alternative text of images should not be repeated as text',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/image-redundant-alt',
  },
  {
    id: 'input-button-name',
    name: 'Input buttons must have discernible text',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/input-button-name',
  },
  {
    id: 'input-image-alt',
    name: 'Image buttons must have alternate text',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/input-image-alt',
  },
  {
    id: 'label-content-name-mismatch',
    name: 'Elements must have their visible text as part of their accessible name',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/label-content-name-mismatch',
  },
  {
    id: 'label-title-only',
    name: 'Form elements should have a visible label',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/label-title-only',
  },
  {
    id: 'label',
    name: 'Form elements must have labels',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/label',
  },
  {
    id: 'landmark-banner-is-top-level',
    name: 'Banner landmark should not be contained in another landmark',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/landmark-banner-is-top-level',
  },
  {
    id: 'landmark-complementary-is-top-level',
    name: 'Aside should not be contained in another landmark',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/landmark-complementary-is-top-level',
  },
  {
    id: 'landmark-contentinfo-is-top-level',
    name: 'Contentinfo landmark should not be contained in another landmark',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/landmark-contentinfo-is-top-level',
  },
  {
    id: 'landmark-main-is-top-level',
    name: 'Main landmark should not be contained in another landmark',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/landmark-main-is-top-level',
  },
  {
    id: 'landmark-no-duplicate-banner',
    name: 'Document should not have more than one banner landmark',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/landmark-no-duplicate-banner',
  },
  {
    id: 'landmark-no-duplicate-contentinfo',
    name: 'Document should not have more than one contentinfo landmark',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/landmark-no-duplicate-contentinfo',
  },
  {
    id: 'landmark-no-duplicate-main',
    name: 'Document should not have more than one main landmark',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/landmark-no-duplicate-main',
  },
  {
    id: 'landmark-one-main',
    name: 'Document should have one main landmark',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/landmark-one-main',
  },
  {
    id: 'landmark-unique',
    name: 'Ensures landmarks are unique',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/landmark-unique',
  },
  {
    id: 'link-in-text-block',
    name: 'Links must be distinguishable without relying on color',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/link-in-text-block',
  },
  {
    id: 'link-name',
    name: 'Links must have discernible text',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/link-name',
  },
  {
    id: 'list',
    name: '<ul> and <ol> must only directly contain <li>, <script> or <template> elements',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/list',
  },
  {
    id: 'listitem',
    name: '<li> elements must be contained in a <ul> or <ol>',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/listitem',
  },
  {
    id: 'marquee',
    name: '<marquee> elements are deprecated and must not be used',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/marquee',
  },
  {
    id: 'meta-refresh-no-exceptions',
    name: 'Delayed refresh must not be used',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/meta-refresh-no-exceptions',
  },
  {
    id: 'meta-refresh',
    name: 'Delayed refresh under 20 hours must not be used',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/meta-refresh',
  },
  {
    id: 'meta-viewport-large',
    name: 'Users should be able to zoom and scale the text up to 500%',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/meta-viewport-large',
  },
  {
    id: 'meta-viewport',
    name: 'Zooming and scaling must not be disabled',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/meta-viewport',
  },
  {
    id: 'nested-interactive',
    name: 'Interactive controls must not be nested',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/nested-interactive',
  },
  {
    id: 'no-autoplay-audio',
    name: '<video> or <audio> elements must not play automatically',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/no-autoplay-audio',
  },
  {
    id: 'object-alt',
    name: '<object> elements must have alternate text',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/object-alt',
  },
  {
    id: 'p-as-heading',
    name: 'Styled <p> elements must not be used as headings',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/p-as-heading',
  },
  {
    id: 'page-has-heading-one',
    name: 'Page should contain a level-one heading',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/page-has-heading-one',
  },
  {
    id: 'presentation-role-conflict',
    name: 'Ensure elements marked as presentational are consistently ignored',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/presentation-role-conflict',
  },
  {
    id: 'region',
    name: 'All page content should be contained by landmarks',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/region',
  },
  {
    id: 'role-img-alt',
    name: '[role="img"] elements must have an alternative text',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/role-img-alt',
  },
  {
    id: 'scope-attr-valid',
    name: 'scope attribute should be used correctly',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/scope-attr-valid',
  },
  {
    id: 'scrollable-region-focusable',
    name: 'Scrollable region must have keyboard access',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/scrollable-region-focusable',
  },
  {
    id: 'select-name',
    name: 'Select element must have an accessible name',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/select-name',
  },
  {
    id: 'server-side-image-map',
    name: 'Server-side image maps must not be used',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/server-side-image-map',
  },
  {
    id: 'skip-link',
    name: 'The skip-link target should exist and be focusable',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/skip-link',
  },
  {
    id: 'svg-img-alt',
    name: '<svg> elements with an img role must have an alternative text',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/svg-img-alt',
  },
  {
    id: 'tabindex',
    name: 'Elements should not have tabindex greater than zero',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/tabindex',
  },
  {
    id: 'table-duplicate-name',
    name: 'tables should not have the same summary and caption',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/table-duplicate-name',
  },
  {
    id: 'table-fake-caption',
    name: 'Data or header cells must not be used to give caption to a data table.',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/table-fake-caption',
  },
  {
    id: 'target-size',
    name: 'All touch targets must be 24px large, or leave sufficient space',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/target-size',
  },
  {
    id: 'td-has-header',
    name: 'Non-empty <td> elements in larger <table> must have an associated table header',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/td-has-header',
  },
  {
    id: 'td-headers-attr',
    name: 'Table cells that use the headers attribute must only refer to cells in the same table',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/td-headers-attr',
  },
  {
    id: 'th-has-data-cells',
    name: 'Table headers in a data table must refer to data cells',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/th-has-data-cells',
  },
  {
    id: 'valid-lang',
    name: 'lang attribute must have a valid value',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/valid-lang',
  },
  {
    id: 'video-caption',
    name: '<video> elements must have captions',
    type: 'a11y',
    url: 'https://dequeuniversity.com/rules/axe/4.9/video-caption',
  },
];

export default {
  BUILD_SCAN_RULES,
};
