############################
#  SHARED

env-cf: &env-cf
  CF_API: https://api.fr.cloud.gov
  CF_USERNAME: ((production-cf-username))
  CF_PASSWORD: ((production-cf-password))
  CF_ORG: gsa-18f-federalist
  CF_SPACE: production

node-image: &node-image
  type: docker-image
  source:
    repository: node
    tag: 16.14

cf-image: &cf-image
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: 18fgsa/concourse-task

test-api: &test-api
  - in_parallel:
    - get: redis
      params: {save: true}
    - get: postgres
      params: {save: true}
    - get: node
      params: {save: true}

  - task: install-deps-api
    config:
      platform: linux
      image_resource:
        <<: *node-image
      inputs: [name: src-api]
      outputs: [name: src-api]
      run:
        dir: src-api
        path: bash
        args: [-c, yarn --pure-lockfile]

  - in_parallel:
    - task: lint-api
      config:
        platform: linux
        image_resource:
          <<: *node-image
        inputs: [name: src-api]
        run:
          dir: src-api
          path: bash
          args: [-c, yarn lint]

    - task: test-api
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: karlkfi/concourse-dcind
        inputs:
          - name: src-api
          - name: redis
          - name: postgres
          - name: node
        run:
          dir: src-api
          path: ci/docker/entrypoint.sh
          args:
            - bash
            - -ceux
            - |
              docker network prune -f
              docker-compose -f ci/docker/docker-compose.yml run app app/ci/tasks/test-api.sh
              docker-compose -f ci/docker/docker-compose.yml down
              docker volume rm $(docker volume ls -q)
              docker network prune -f

test-admin-client: &test-admin-client
  - task: install-deps-admin-client
    config:
      platform: linux
      image_resource:
        <<: *node-image
      inputs: [name: src-admin-client]
      outputs: [name: src-admin-client]
      run:
        dir:  src-admin-client/admin-client
        path: bash
        args: [-c, yarn --pure-lockfile]

  - task: lint-admin-client
    config:
      platform: linux
      image_resource:
        <<: *node-image
      inputs: [name: src-admin-client]
      run:
        dir: src-admin-client/admin-client
        path: bash
        args: [-c, yarn lint]

  - task: build-admin-client
    config:
      platform: linux
      image_resource:
        <<: *node-image
      inputs: [name: src-admin-client]
      outputs: [name: src-admin-client]
      params:
        API_URL: https://federalistapp.18f.gov
        NODE_ENV: production
      run:
        dir: src-admin-client/admin-client
        path: bash
        args: [-c, yarn build]

############################
#  JOBS

jobs:

  - name: test-api-federalist
    plan:
      - get: src-api
        resource: pr-production
        trigger: true
        version: every
      - put: src-api
        resource: pr-production
        params:
          path: src-api
          status: pending
          base_context: concourse
          context: test-api-federalist
      - do: *test-api

    on_failure:
      in_parallel:
        - put: src-api
          resource: pr-production
          params:
            path: src-api
            status: failure
            base_context: concourse
            context: test-api-federalist
        - put: slack
          params:
            text: |
              :x: FAILED: federalist api tests on production
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

    on_success:
      in_parallel:
        - put: src-api
          resource: pr-production
          params:
            path: src-api
            status: success
            base_context: concourse
            context: test-api-federalist
        - put: slack
          params:
            text: |
              :white_check_mark: SUCCESS: Successfully tested federalist api on production
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: test-admin-client-federalist
    plan:
      - get: src-admin-client
        resource: pr-production
        trigger: true
        version: every
      - put: src-admin-client
        resource: pr-production
        params:
          path: src-admin-client
          status: pending
          base_context: concourse
          context: test-admin-client-federalist

      - do: *test-admin-client

    on_failure:
      in_parallel:
        - put: src-admin-client
          resource: pr-production
          params:
            path: src-admin-client
            status: failure
            base_context: concourse
            context: test-admin-client-federalist
        - put: slack
          params:
            text: |
              :x: FAILED: federalist admin client tests on production
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

    on_success:
      in_parallel:
        - put: src-admin-client
          resource: pr-production
          params:
            path: src-admin-client
            status: success
            base_context: concourse
            context: test-admin-client-federalist
        - put: slack
          params:
            text: |
              :white_check_mark: SUCCESS: Successfully tested federalist admin client on production
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: test-and-deploy-api-federalist
    plan:
      - get: src-api
        resource: src-production
        # passed: [set-pipeline]
        trigger: true
        params: {depth: 1}
      - put: gh-status
        inputs: [src-api]
        params: {state: pending}
      - do: *test-api
      - task: build-api
        config:
          platform: linux
          image_resource:
            <<: *node-image
          inputs: [name: src-api]
          outputs: [name: src-api]
          params:
            APP_HOSTNAME: https://federalistapp.18f.gov
            PRODUCT: federalist
          run:
            dir: src-api
            path: bash
            args: [-c, yarn build]

      - task: deploy-api
        config:
          <<: *cf-image
          inputs: [name: src-api]
          run:
            path: src-api/ci/tasks/deploy.sh
        params:
          <<: *env-cf
          CF_APP_NAME: federalistapp
          CF_MANIFEST: src-api/.cloudgov/manifest.yml
          CF_VARS_FILE: src-api/.cloudgov/vars/production.yml
          CF_PATH: src-api
        on_failure:
          try:
            task: cancel-api-deployment
            config:
              <<: *cf-image
              inputs: [name: src-api]
              run:
                path: src-api/ci/tasks/cancel-deployment.sh
            params:
              <<: *env-cf
              CF_APP_NAME: federalistapp

      - task: run-database-migrations
        config:
          <<: *cf-image
          inputs: [name: src-api]
          run:
            path: src-api/ci/tasks/run-task.sh
        params:
          <<: *env-cf
          CF_APP_NAME: federalistapp
          CF_TASK_NAME: run-migrations
          CF_TASK_COMMAND: 'yarn run migrate:up'
        on_failure:
          in_parallel:
            - put: gh-status
              inputs: [src-api]
              params: {state: failure}
            - put: slack
              params:
                text: |
                  :x: FAILED: to migrate database for federalist production
                  <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
                channel: ((slack-channel))
                username: ((slack-username))
                icon_url: ((slack-icon-url))

    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src-api]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: api deployment on federalist production)
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))
    on_success:
      in_parallel:
        - put: gh-status
          inputs: [src-api]
          params: {state: success}
        - put: slack
          params:
            text: |
              :white_check_mark: SUCCESS: Successfully deployed api on federalist production
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: test-and-deploy-admin-client-federalist
    plan:
      - get: src-admin-client
        resource: src-production
        # passed: [set-pipeline]
        trigger: true
        params: {depth: 1}
      - put: gh-status
        inputs: [src-admin-client]
        params: {state: pending}

      - do: *test-admin-client

      - task: configure-nginx
        config:
          <<: *cf-image
          inputs: [name: src-admin-client]
          outputs: [name: src-admin-client]
          run:
            dir: src-admin-client
            path: ci/tasks/configure-admin-client-nginx.sh
        params:
          API_DOMAIN: federalistapp.18f.gov

      - task: deploy-admin-client-federalist
        config:
          <<: *cf-image
          inputs: [name: src-admin-client]
          run:
            dir: src-admin-client
            path: ci/tasks/deploy.sh
        params:
          <<: *env-cf
          CF_APP_NAME: federalist-admin
          CF_MANIFEST: .cloudgov/manifest.yml
          CF_VARS_FILE: .cloudgov/vars/production.yml
          CF_PATH: admin-client
        on_failure:
          try:
            task: cancel-admin-client-deployment
            config:
              <<: *cf-image
              inputs: [name: src-admin-client]
              run:
                dir: src-admin-client
                path: ci/tasks/cancel-deployment.sh
            params:
              <<: *env-cf
              CF_APP_NAME: federalist-admin

    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src-admin-client]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: admin client deployment on federalist production
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

    on_success:
      in_parallel:
        - put: gh-status
          inputs: [src-admin-client]
          params: {state: success}
        - put: slack
          params:
            text: |
              :white_check_mark: SUCCESS: Successfully deployed admin client on federalist production
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: nightly-tasks-federalist
    plan:
      - get: src
        resource: src-production
        # passed: [set-pipeline]
        params: {depth: 1}
      - get: nightly
        trigger: true
      - in_parallel:
        - task: restage-api
          config:
            inputs: [name: src]
            <<: *cf-image
            run:
              path: src/ci/tasks/restage.sh
          params:
            <<: *env-cf
            CF_APP_NAME: federalistapp
        - task: restage-admin
          config:
            inputs: [name: src]
            <<: *cf-image
            run:
              path: src/ci/tasks/restage.sh
          params:
            <<: *env-cf
            CF_APP_NAME: federalist-admin

  - name: sites-builds-checks-federalist
    plan:
      - get: src
        resource: src-production
        # passed: [set-pipeline]
        params: {depth: 1}
      - get: five-minutes
        trigger: true
      - in_parallel:
        - task: queued-builds-check
          config:
            inputs: [name: src]
            <<: *cf-image
            run:
              path: src/ci/tasks/run-task.sh
          params:
            <<: *env-cf
            CF_APP_NAME: federalistapp
            CF_TASK_NAME: queued-builds-check
            CF_TASK_COMMAND: yarn queued-builds-check ((support-email))
        on_failure:
          in_parallel:
            - put: slack
              params:
                text: |
                  :x: FAILED: sites builds checks on federalist production
                  <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
                channel: ((slack-channel))
                username: ((slack-username))
                icon_url: ((slack-icon-url))

  - name: set-pipeline
    plan:
    - get: src
      resource: src-production
      params: {depth: 1}
      trigger: true
    - set_pipeline: federalist-core
      file: src/ci/federalist-pipeline.yml

############################
#  RESOURCES

resources:

  - name: pr-production
    type: pull-request
    check_every: 1m
    source:
      repository: ((pages-repository-path))
      access_token: ((gh-access-token))
      base_branch: main
      disable_forks: true
      ignore_drafts: false

  - name: src-production
    type: git
    icon: github
    source:
      uri: ((git-base-url))/((pages-repository-path))
      branch: main

  - name: nightly
    type: time
    source:
      start: 12:00 AM
      stop: 1:00 AM
      location: America/New_York

  - name: five-minutes
    type: time
    source:
      interval: 5m

  - name: redis
    type: docker-image
    source:
      repository: redis
      tag: 5-alpine

  - name: postgres
    type: docker-image
    source:
      repository: postgres
      tag: 11-alpine

  - name: node
    type: docker-image
    source:
      repository: node
      tag: 16.14

  - name: slack
    type: slack-notification
    source:
      url: ((slack-webhook-url))

  - name: gh-status
    type: cogito
    check_every: 1h
    source:
      owner: 18F
      repo: federalist
      access_token: ((gh-access-token))
      context_prefix: concourse


############################
#  RESOURCE TYPES

resource_types:

  - name: cogito
    type: docker-image
    check_every: 24h
    source:
      repository: pix4d/cogito

  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
